### ISSUE TITLE
Ajustar etiqueta

### ISSUE THREAD

**Issue by JuniorYepes** [FelipeDRZ/Nuevo#3]
Una etiqueta div no puede ir sola, porque no haría nada, como buena práctica usar una clase o no usarse
https://github.com/FelipeDRZ/Nuevo/blob/2d534db59eaef6dd215650c8574a278b878abd4c/index.html#L16

**Comment by FelipeDRZ** [comment]
la etiqueta dic ya cuenta con su propiedad de class="container"
